version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2015
platform: x64

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\win_build.bat'

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\test\test_libpostal.exe'
