language: c
env:
    global:
        - secure: "bHrAu46oecEj3gjamT+XWXtf2J0ZJCFa8tUdgM4evscaJiiwv1TtsGXyhIj/ai7DlRIPVJUtBUy6uoGGjr6GT43zTrzSxYAOMdVXZYsnTDcdL1/0dbwcIK6/u0EI377s1buGIxG1fHveWKXuXwJWDAw4KS+5HU88a42+zMbhKe4="
        - secure: "SkvNYucKVns9qDjOEW2WIhDlOMKBOwhzVcwY++HWTRtn04ErrqR4k01Mmho0jGBQD9JrPLhDgnX1BNy5s+Kmq/bxn9OZm7K1z24qBKb0mBBiNEnf2jvT0AvF5xxM+cJf4KKNL+CC0MwNf5y7HVPq1xibOV4/CNIrc1ZZc9aqdkE="
compiler:
    - clang
    - gcc
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - libsnappy-dev
before_script:
    - ./bootstrap.sh
    - export DICTIONARIES_CHANGED=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep "resources/dictionaries" | wc -l)
    - export NUMEX_CHANGED=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep "resources/numex" | wc -l)
    - export TRANSLIT_CHANGED=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep "src/transliteration_data.c" | wc -l)
    - if [ $DICTIONARIES_CHANGED -ne 0 || $NUMEX_CHANGED -ne 0 ]; then pip install -r scripts/requirements-simple.txt; fi;
    - if [ $NUMEX_CHANGED -ne 0 ]; then python scripts/geodata/i18n/numex.py; fi;
    - if [ $DICTIONARIES_CHANGED -ne 0 ]; then python scripts/geodata/address_expansions/address_dictionaries.py; fi;
install:
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
script:
    - ./configure --datadir=$(pwd)/data
    - make
    - if [ "$CC" = "gcc" && $DICTIONARIES_CHANGED -ne 0 ]; then ./src/build_address_dictionary; fi;
    - if [ "$CC" = "gcc" && $NUMEX_CHANGED -ne 0 ]; then ./src/build_numex_table; fi;
    - if [ "$CC" = "gcc" && $TRANSLIT_CHANGED -ne 0 ]; then ./src/build_trans_table; fi;
    - make check
after_success:
    - if [[ "$CC" = "gcc" && "${TRAVIS_PULL_REQUEST}" = "false" && ( $DICTIONARIES_CHANGED -ne 0 || $NUMEX_CHANGED -ne 0 || $TRANSLIT_CHANGED -ne 0 ) ]]; then ./src/libpostal_data upload base $(pwd)/data/libpostal; git commit -a -m "[auto][build] Adding data files"; git push; fi;
