language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
        - libsnappy-dev
        - pkg-config
        - autoconf-archive
before_script:
    - ./bootstrap.sh
script:
    - ./configure
    - travis_wait make
    - make check
