language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - libsnappy-dev
before_script:
    - ./bootstrap.sh
install:
    - if [ "$CC" = "gcc ]; then export CC="gcc-4.8"; fi
script:
    - ./configure --datadir=$(pwd)/data
    - make
    - make check
