language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
        - libsnappy-dev
        - pkg-config
        - autoconf
        - automake
        - libtool
        - autoconf-archive
script:
    - ./bootstrap.sh
    - ./configure
    - make
    - make check
